mode: train
train:
  dataset: MvRgbDatasetAvatarReX
  data:
    subject_name: avatarrex_lbn_compact
    data_dir: ./data/avatarrex/lbn_compact
    pos_map_mode: compact
    frame_range: &id001
    - 0
    - 1871
    - 1
    used_cam_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 8
    - 9
    - 10
    - 11
    - 12
    - 14
    - 15
    load_smpl_pos_map: true
  pretrained_dir: null
  net_ckpt_dir: ./results/avatarrex_lbn_compact/avatar
  prev_ckpt: null
  ckpt_interval:
    epoch: 10
    batch: 50000
  eval_interval: 1000
  eval_training_ids: [2, 0]
  eval_testing_ids: [481, 0]
  eval_img_factor: 1.0
  lr_init: 0.0005
  loss_weight:
    l1: 1.0
    lpips: 0.1
    offset: 0.005
    scaling: 1.0
    cano_offset: 0.
  finetune_color: false
  batch_size: 1
  num_workers: 8
  random_bg_color: true
  gs_lr_scale: 3.0
  iteration_lpips_random_patch: 200000
  iteration_lpips_start: 2000
  pretrain_iter_num: 2000
  # lr_xyz: 0.00016
  lr_offset: 0.001
  lr_opacity: 0.0005
  lr_scale: 0.0005
  lr_rotation: 0.0005
  lr_features_dc: 0.0005
  lr_features_rest: 0.0005
test:
  dataset: MvRgbDatasetAvatarReX
  data:
    data_dir: ./data/avatarrex/lbn_compact
    frame_range: [0, 500]
    subject_name: avatarrex_lbn_compact
  # pose_data:
  #   data_path: ./data/pose/thuman4/pose_00.npz
  #   frame_range: [2000, 2500]
#    data_path: Z:/Data/Pose/AMASS/CMU/06/06_13_poses.npz
#    data_path: Z:/Data/Pose/AMASS/CMU/10/10_05_poses.npz
#    frame_interval: 4
  view_setting: camera
  render_view_idx: 1
  global_orient: true
  img_scale: 1.0
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_cano_offset: false
  save_ply: false
  render_gaussian_only: false
  n_pca: 20
  sigma_pca: 2.0
  prev_ckpt: ./results/avatarrex_lbn_compact/avatar/batch_700000
model:
  with_viewdirs: true
  random_style: false
  pred_color_offset: true
  multires_pe: 6
  max_sh_degree: 0
  add_global: true
  fix_cano_xyz: false
  opt_xyz_offset: true
  faster: true