mode: train
train:
  dataset: MvRgbDatasetActorsHQ
  data:
    subject_name: actor08
    data_dir: Z:/Data/MultiviewRGB/ActorsHQ/Actor08/Sequence1
    frame_range: &id001
    - 63
    - 2374
    - 1
    used_cam_ids: [4, 5, 6, 7, 20, 21, 22, 23, 36, 37, 38, 39, 52, 53, 54, 55, 76, 77, 78, 79, 92, 93, 94, 95, 108, 109, 110, 111, 125, 126, 127, 130, 131, 134, 135, 138, 139, 142, 143, 146, 147, 150, 151, 154, 155, 158, 159]
    load_smpl_pos_map: true
  pretrained_dir: null
  net_ckpt_dir: ./results/actor08/avatar
  prev_ckpt: null
  ckpt_interval:
    epoch: 100
    batch: 50000
  eval_interval: 1000
  eval_training_ids: [710, 127]
  eval_testing_ids: [1459, 127]
  eval_img_factor: 1.0
  lr_init: 0.0005
  loss_weight:
    l1: 1.0
    ssim: 0.2
    lpips: 1.0
    gan: 0.
    offset: 0.
  finetune_color: false
  batch_size: 1
  num_workers: 8
  random_bg_color: true
test:
  dataset: MvRgbDatasetActorsHQ
  data:
    data_dir: Z:/Data/MultiviewRGB/ActorsHQ/Actor08/Sequence1
    frame_range: *id001
    subject_name: actor08
  pose_data:
    data_path: Z:/Data/Pose/AMASS/MPI_mosh/00059/misc_poses.npz
    frame_interval: 4
  view_setting: front
  render_view_idx: 0
  global_orient: true
  img_scale: 1.0
  save_mesh: false
  render_skeleton: false
  save_tex_map: false
  save_ply: false
  n_pca: 20
  sigma_pca: 2.0
  prev_ckpt: ./results/actor08/avatar/batch_800000
model:
  with_viewdirs: true
  random_style: false